blank_issues_enabled: false
contact_links:
  - name: TanStack Starter Community Support
    url: https://mksaas.link/discord
    about: Please ask and answer questions here.
  - name: TanStack Starter Documentation
    url: https://docs.tanstackstarter.dev
    about: Please check out the documentation here.
